'''
Get data for sensors using rx and write it to InfluxDB

Check guide and requirements from post_to_influxdb.py
'''

from influxdb import InfluxDBClient
from ruuvitag_sensor.ruuvi_rx import RuuviTagReactive

client = InfluxDBClient(host="localhost", port=8086, database="ruuvi")


def write_to_influxdb(received_data):
    json_body = []
    for field in ['temperature', 'humidity', 'pressure']:
        json_body.append({
            "measurement": field,
            "tags": {
                "mac": received_data[0],
                "protocolVersion": 3,
            },
            "fields": {
                "value": received_data[1][field]
            }
        })

    client.write_points(json_body)


interval_in_ms = 5000

ruuvi_rx = RuuviTagReactive()

# Makes separate write to influxdb for each sensor as each subject generated by group_by is handled separately
ruuvi_rx.get_subject().\
    group_by(lambda x: x[0]).\
    subscribe(lambda x: x.sample(interval_in_ms).subscribe(write_to_influxdb))
